#!/usr/bin/env python3
"""Turn art/*.txt into sprites.h (bitmaps + opacity masks, MSB-first rows)."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "art")

# 3x5 font for the side panel
FONT = {
    "0": ["###", "#.#", "#.#", "#.#", "###"],
    "1": [".#.", "##.", ".#.", ".#.", "###"],
    "2": ["###", "..#", "###", "#..", "###"],
    "3": ["###", "..#", ".##", "..#", "###"],
    "4": ["#.#", "#.#", "###", "..#", "..#"],
    "5": ["###", "#..", "###", "..#", "###"],
    "6": ["###", "#..", "###", "#.#", "###"],
    "7": ["###", "..#", ".#.", ".#.", ".#."],
    "8": ["###", "#.#", "###", "#.#", "###"],
    "9": ["###", "#.#", "###", "..#", "###"],
    "S": [".##", "#..", ".#.", "..#", "##."],
    "C": [".##", "#..", "#..", "#..", ".##"],
    "O": [".#.", "#.#", "#.#", "#.#", ".#."],
    "R": ["##.", "#.#", "##.", "#.#", "#.#"],
    "E": ["###", "#..", "##.", "#..", "###"],
    "H": ["#.#", "#.#", "###", "#.#", "#.#"],
    "I": ["###", ".#.", ".#.", ".#.", "###"],
    "L": ["#..", "#..", "#..", "#..", "###"],
    "V": ["#.#", "#.#", "#.#", "#.#", ".#."],
    "P": ["##.", "#.#", "##.", "#..", "#.."],
    "A": [".#.", "#.#", "###", "#.#", "#.#"],
    "U": ["#.#", "#.#", "#.#", "#.#", "###"],
    "T": ["###", ".#.", ".#.", ".#.", ".#."],
    "N": ["#.#", "###", "###", "#.#", "#.#"],
    "G": [".##", "#..", "#.#", "#.#", ".##"],
    "M": ["#.#", "###", "###", "#.#", "#.#"],
    "F": ["###", "#..", "##.", "#..", "#.."],
    "D": ["##.", "#.#", "#.#", "#.#", "##."],
    "X": ["#.#", "#.#", ".#.", "#.#", "#.#"],
    "W": ["#.#", "#.#", "###", "###", "#.#"],
    "K": ["#.#", "#.#", "##.", "#.#", "#.#"],
    "Y": ["#.#", "#.#", ".#.", ".#.", ".#."],
    "B": ["##.", "#.#", "##.", "#.#", "##."],
    " ": ["...", "...", "...", "...", "..."],
    ":": ["...", ".#.", "...", ".#.", "..."],
    "-": ["...", "...", "###", "...", "..."],
}


def read_sprites(path):
    sprites = []
    name, flags, rows = None, [], []
    for line in open(path):
        line = line.rstrip("\n")
        if line.startswith("#") and not set(line) <= set("#."):
            continue
        if line.startswith("@"):
            if name:
                sprites.append((name, flags, rows))
            parts = line[1:].split()
            name, flags, rows = parts[0], parts[1:], []
        elif line.strip() and name:
            rows.append(line.strip())
    if name:
        sprites.append((name, flags, rows))
    return sprites


def check(name, rows):
    w = len(rows[0])
    for r in rows:
        if len(r) != w or set(r) - set("#."):
            sys.exit(f"{name}: bad row {r!r}")


def mask_of(rows):
    h, w = len(rows), len(rows[0])
    outside = [[False] * w for _ in range(h)]
    stack = [(y, x) for y in range(h) for x in range(w)
             if (y in (0, h - 1) or x in (0, w - 1)) and rows[y][x] == "."]
    while stack:
        y, x = stack.pop()
        if outside[y][x] or rows[y][x] != ".":
            continue
        outside[y][x] = True
        for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            ny, nx = y + dy, x + dx
            if 0 <= ny < h and 0 <= nx < w:
                stack.append((ny, nx))
    return ["".join("." if outside[y][x] else "#" for x in range(w)) for y in range(h)]


def pack(rows):
    out = []
    for r in rows:
        for i in range(0, len(r), 8):
            chunk = r[i:i + 8].ljust(8, ".")
            out.append(int("".join("1" if c == "#" else "0" for c in chunk), 2))
    return out


def c_array(name, data):
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    return f"static const uint8_t {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def emit(out, name, rows, masked):
    check(name, rows)
    out.append(c_array(f"{name}_bits", pack(rows)))
    mask = "NULL"
    if masked:
        m = mask_of(rows)
        if any("." in r for r in m):
            out.append(c_array(f"{name}_mask", pack(m)))
            mask = f"{name}_mask"
    out.append(
        f"static const Sprite spr_{name} = {{{len(rows[0])}, {len(rows)}, {name}_bits, {mask}}};\n")


def main():
    out = [
        "// Generated by tools/gen_sprites.py from art/*.txt. Do not edit.\n",
        "#pragma once\n#include <stdint.h>\n#include <stddef.h>\n",
        "typedef struct {\n    uint8_t w, h;\n    const uint8_t* bits;\n"
        "    const uint8_t* mask; // NULL = fully opaque\n} Sprite;\n",
    ]
    for fname, name in (("background.txt", "background"), ("logo.txt", "logo")):
        rows = [r.strip() for r in open(os.path.join(ART, fname)) if r.strip()]
        emit(out, name, rows, masked=False)
    for name, flags, rows in read_sprites(os.path.join(ART, "sprites.txt")):
        emit(out, name, rows, masked="opaque" not in flags)
        if "mirror" in flags:
            base = name[:-2] if name.endswith("_r") else name
            mname = base + "_l" if name.endswith("_r") else name.replace("_r", "_l", 1)
            emit(out, mname, [r[::-1] for r in rows], masked=True)
    glyphs = sorted(FONT)
    font_bytes = []
    for ch in glyphs:
        for r in FONT[ch]:
            font_bytes.append(int("".join("1" if c == "#" else "0" for c in r), 2) << 5)
    out.append("static const char font3x5_chars[] = \"" +
               "".join(glyphs).replace("\\", "\\\\") + "\";\n")
    out.append(c_array("font3x5", font_bytes))
    open(os.path.join(ROOT, "sprites.h"), "w").write("\n".join(out))


if __name__ == "__main__":
    main()
